save_csv:
  data_list: []

test:
  randomseed: 777
  spk: 2
  duration: 64000 # sample
  fs: 16000
  speech_least_chunk_size: 16000

# randomseed: 777

each_spk_dict:
  speech_wav: 
  azi:
  speech_loc:
  ref_snr: 
  speech_start_point:
  speech_duration:
  speech_pos_in_file:
  speech_pos_type:  # mid, back, front



save_dict:
  num_spk:
  normalize_factor: 

  spk_list: []

  mic:
    mic_pos: #x, y, z
    mic_center_loc: # x,y,z
    theta: 

  noise:
    noise_wav:
    noise_start_point:
    SNR:
    azi:
    noise_loc: 

  room_sz: 
  T_max: 
  att_max: 
  att_diff: 
  abs_weight: 

test_with_big_reverb:
  data_csv_dir: ../config/data_csv/
  data_dict_dir: ../config/eval_big_reverb_dict/
  room_character_dict: room_character.yaml
  noise_csv: noise_test.csv
  speech_csv: test_audio_list.csv
  SNR: [-5, 20]
  speech_snr: [-5, 5]
  rir_csv: test_rir_room.csv
  save_csv: beamforming_test_with_big_reverb.csv
  normalize_factor: [-20, -40]
  train_len: 64000 # 4s

  mic:
    rotation: True
    mic_shape: ['circle']
    mic_num: [8,8] # range
    mic_height: [0.6, 1.1] # m, mic 높이
    mic_from_wall: 0.25 # mic가 벽에서 떨어져 있는 거리 (m)

  room:
    sound_velocity: 343
    rt60_bound: [0.05, 0.7]
    att_diff: [10.0, 15.0]
    att_max: [60.0, 90.0]
    abs_weights_bound: [0.5, 1.0]
    room_sz_bound:
      x: [2.5, 10.0]
      y: [2.5, 10.0]
      z: [2.5, 5.0]

  sound_pos:
    distance: [0.5, 2.0] # m
    azimuth: [0, 360, 5] # start, end, unit # degree
    elevation: [0, 35, 5]

test:
  data_csv_dir: ../config/data_csv/
  data_dict_dir: ../config/eval_dict/
  room_character_dict: room_character.yaml
  noise_csv: noise_test.csv
  speech_csv: test_audio_list.csv
  SNR: [-5, 20]
  speech_snr: [-5, 5]
  rir_csv: test_rir_room.csv
  save_csv: beamforming_test.csv
  normalize_factor: [-20, -40]
  train_len: 64000

  mic:
    rotation: True
    mic_shape: ['circle']
    mic_num: [8,8]
    mic_height: [0.6, 1.1] # m, mic 높이
    mic_from_wall: 0.25 # mic가 벽에서 떨어져 있는 거리 (m)

  sound_pos:
    distance: [0.5, 2.0] # m
    azimuth: [0, 360, 5] # start, end, unit # degree
    elevation: [0, 35, 5]

val:
  data_csv_dir: ../config/data_csv/
  data_dict_dir: ../config/val_dict/
  room_character_dict: room_character.yaml
  noise_csv: noise_cv.csv
  speech_csv: cv_audio_list.csv
  SNR: [0, 20]
  speech_snr: [-5, 5]
  rir_csv: train_rir_room.csv
  save_csv: beamforming_val.csv
  normalize_factor: [-20, -40]
  train_len: 64000 # 4s

  mic:
    rotation: True
    mic_shape: ['linear'] # circle
    mic_num: [8,8] # range
    mic_height: [0.6, 1.1] # m, mic 높이
    mic_from_wall: 0.25 # mic가 벽에서 떨어져 있는 거리 (m)

  room:
    sound_velocity: 343
    rt60_bound: [0.05, 0.3]
    att_diff: [10.0, 15.0]
    att_max: [60.0, 90.0]
    abs_weights_bound: [0.5, 1.0]
    room_sz_bound:
      x: [2.5, 10.0]
      y: [2.5, 10.0]
      z: [2.5, 5.0]

  sound_pos:
    distance: [0.5, 2.0] # m
    azimuth: [0, 360, 1] # start, end, unit # degree
    elevation: [0, 35, 5]